name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: Version

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Windows Build
            os: windows-latest
            architecture: x64
            artifact: windows
            upload_path_suffix: '/*'
          - name: Linux Build
            os: ubuntu-24.04
            architecture: x64
            artifact: linux
            upload_path_suffix: '/*'
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libgtkmm-4.0-dev
      - name: Set up MSVC for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup cmake
        uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: 'cf035d9916a0a23042b41fcae7ee0386d245af08'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'
      - name: Integrate vcpkg
        if: runner.os == 'Windows'
        run: |
          vcpkg install gtkmm
          vcpkg integrate install
      - name: Run CMake
        uses: lukka/run-cmake@v3.3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: '${{ github.workspace }}/build'
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: '-G Ninja'
      - name: Create App Package Linux
        if: runner.os == 'Linux'
        run: |
          mkdir gctools-build
          cp build/gctoolsui gctools-build/gctoolsui
          cp build/*.ui gctools-build
      - name: Create App Package Windows
        if: runner.os == 'Windows'
        run: |
          mkdir gctools-build
          cp build/gctoolsui.exe gctools-build/gctoolsui.exe
          cp build/*.dll gctools-build
          cp build/*.ui gctools-build
      - name: Upload App Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: gctools-windows
          path: gctools-build
      - name: Upload App Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: gctools-linux
          path: gctools-build